name: deploy-aws-lambda

on:
  push:
    branches:
      - deploy-test
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  call-test-workflow:
    uses: ./.github/workflows/run-tests-on-pull-request.yaml
    secrets: inherit

  call-deploy-workflow:
    needs: call-test-workflow
    uses: daily-science/nshm-github-actions/.github/workflows/deploy-to-aws.yml@main
    with:
      python-version: '3.12'
      node-version: '22'
      node-pkg-manager: 'yarn2'
      smoketest-query: 'query QueryRoot{about}'
    secrets: inherit